# Generated by Django 3.0.1 on 2019-12-30 13:26

from django.db import migrations, models


def create_weekdays(apps, schema_editor):

    Weekday = apps.get_model("api", "Weekday")

    weekday_list = [
        {'day' : 'Monday', 'iso_weekday' : 1},
        {'day' : 'Tuesday', 'iso_weekday' : 2},
        {'day' : 'Wednesday', 'iso_weekday' : 3},
        {'day' : 'Thursday', 'iso_weekday' : 4},
        {'day' : 'Friday', 'iso_weekday' : 5},
        {'day' : 'Saturday', 'iso_weekday' : 6},
        {'day' : 'Sunday', 'iso_weekday' : 7},
    ]

    weekdays = []
    for day_of_week in weekday_list:
        weekday = Weekday(
            day = day_of_week['day'],
            iso_weekday = day_of_week['iso_weekday']
        )

        weekdays.append(weekday)

    Weekday.objects.bulk_create(weekdays)

def reverse_func(apps, schema_editor):

    Weekday = apps.get_model("api", "Weekday")
    Weekday.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schedule_weekday'),
    ]

    operations = [
        migrations.RunPython(create_weekdays, reverse_func),
    ]
