# Generated by Django 3.0.1 on 2020-01-01 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_from_csv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['weekday__iso_weekday']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='add_overflow',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.Restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('restaurant', 'weekday')},
        ),
    ]
