# Generated by Django 3.0.1 on 2020-01-01 23:59

from django.db import migrations, models

def check_overflow(apps, schema_editor):
    """Update days that have overflowing schedules"""

    Restaurant = apps.get_model("api", "Restaurant")
    Schedule = apps.get_model("api", "Schedule")

    restaurants = Restaurant.objects.all()

    for restaurant in restaurants:

        schedules = Schedule.objects.filter(restaurant_id=restaurant.id)
        for i in schedules:

            iso_w = i.weekday.iso_weekday + 1
            if iso_w > 7:
                iso_w = 1
                
            if i.opening_time > i.closing_time:
                schedule = Schedule.objects.filter(
                                restaurant_id = restaurant.id,
                                weekday__iso_weekday = iso_w
                            ).first()
                schedule.add_overflow = i.closing_time
                schedule.save()


def reverse_func(apps, schema_editor):

    # Weekday = apps.get_model("api", "Weekday")
    # Weekday.objects.all().delete()
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200102_0259'),
    ]

    operations = [
        migrations.RunPython(check_overflow, reverse_func),
    ]
